// API actionTypes
export const USER_LOGGIN_SUCCESS = "USER_LOGGIN_SUCCESS"
export const USER_LOGGIN_FAILURE = "USER_LOGGIN_FAILURE"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE"

export const FETCH_USER_TRANSACTIONS_START = 'FETCH_USER_TRANSACTIONS_START'
export const FETCH_USER_TRANSACTIONS_SUCCESS = 'FETCH_USER_TRANSACTIONS_SUCCESS'
export const FETCH_USER_TRANSACTIONS_FAILURE = 'FETCH_USER_TRANSACTIONS_FAILURE'

export const FETCH_USERS_LIST_START = 'FETCH_USERS_LIST_START'
export const FETCH_USERS_LIST_SUCCESS = 'FETCH_USERS_LIST_SUCCESS'
export const FETCH_USERS_LIST_FAILURE = 'FETCH_USERS_LIST_FAILURE'

export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"

// App actionTypes
export const OPEN_MODAL_USER_TRANSACTIONS = "OPEN_MODAL_USER_TRANSACTIONS"
export const CLOSE_MODAL_USER_TRANSACTIONS = "CLOSE_MODAL_USER_TRANSACTIONS"
