// API actionTypes
export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS'
export const USER_LOGGED_OUT_FAILURE = 'USER_LOGGED_OUT_FAILURE'

export const USER_SIGNUP_START = 'USER_SIGNUP_START'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const FETCH_USER_TRANSACTIONS_START = 'FETCH_USER_TRANSACTIONS_START'
export const FETCH_USER_TRANSACTIONS_SUCCESS = 'FETCH_USER_TRANSACTIONS_SUCCESS'
export const FETCH_USER_TRANSACTIONS_FAILURE = 'FETCH_USER_TRANSACTIONS_FAILURE'

export const FETCH_USERS_LIST_START = 'FETCH_USERS_LIST_START'
export const FETCH_USERS_LIST_SUCCESS = 'FETCH_USERS_LIST_SUCCESS'
export const FETCH_USERS_LIST_FAILURE = 'FETCH_USERS_LIST_FAILURE'

export const CREATE_TRANSACTION_START = 'CREATE_TRANSACTION_START'
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE'

// App actionTypes
export const GO_TO_SIGNIN_FORM = 'GO_TO_SIGNIN_FORM'
export const GO_TO_SIGNUP_FORM = 'GO_TO_SIGNUP_FORM'
